# Generated by Django 4.0.4 on 2022-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('classication', models.CharField(choices=[(0, 'No'), (1, 'Yes')], max_length=20)),
                ('pipeline', models.CharField(choices=[(0, 'Engine 1'), (1, 'Engine 2'), (2, 'Engine 3')], max_length=20)),
            ],
        ),
    ]
