# Generated by Django 4.0.4 on 2022-06-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_configurenewprocess_classification_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurenewprocess',
            old_name='timezon',
            new_name='time_zon',
        ),
    ]
