# Generated by Django 4.0.4 on 2022-06-27 10:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_timezon_configurenewprocess_time_zon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Regular Model'), ('1', 'Vg16 Model')], max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('threshold', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploads/')),
                ('epochs', models.CharField(choices=[('0', '20'), ('1', '30'), ('2', '40'), ('3', '50'), ('4', '60'), ('5', '70'), ('6', '80'), ('7', '90'), ('8', '100')], max_length=10)),
                ('batch', models.CharField(choices=[('0', '16'), ('1', '32'), ('2', '64')], max_length=10)),
                ('kernel', models.CharField(choices=[('0', 'HE_Normal'), ('1', 'HE_UI_Form')], max_length=10)),
                ('optimizer', models.CharField(choices=[('0', 'adam'), ('1', 'sgd'), ('2', 'rmsprop')], max_length=10)),
                ('text', models.CharField(choices=[('0', '0.3'), ('1', '0.15'), ('2', '0.18'), ('3', '0.21'), ('4', '0.24'), ('5', '0.27')], max_length=10)),
                ('activation', models.CharField(choices=[('0', 'relu'), ('1', 'Leaky_relu')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='configurenewprocess',
            name='input_doc',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('0', 'JPG'), ('1', 'PDF'), ('2', 'JPEG'), ('3', 'TIF'), ('4', 'PNG')], max_length=20),
        ),
    ]
