# Generated by Django 4.0.4 on 2022-06-29 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_processmanagement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processmanagement',
            name='file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['zip'])]),
        ),
    ]
